/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as appNewsletterUnsubscribeRouteImport } from "./routes/(app)/newsletter/unsubscribe"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const appNewsletterUnsubscribeRoute =
  appNewsletterUnsubscribeRouteImport.update({
    id: "/(app)/newsletter/unsubscribe",
    path: "/newsletter/unsubscribe",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/newsletter/unsubscribe": typeof appNewsletterUnsubscribeRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/newsletter/unsubscribe": typeof appNewsletterUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/(app)/newsletter/unsubscribe": typeof appNewsletterUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/newsletter/unsubscribe"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/newsletter/unsubscribe"
  id: "__root__" | "/" | "/(app)/newsletter/unsubscribe"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appNewsletterUnsubscribeRoute: typeof appNewsletterUnsubscribeRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(app)/newsletter/unsubscribe": {
      id: "/(app)/newsletter/unsubscribe"
      path: "/newsletter/unsubscribe"
      fullPath: "/newsletter/unsubscribe"
      preLoaderRoute: typeof appNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appNewsletterUnsubscribeRoute: appNewsletterUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
